### ISSUE TITLE
No access to directory after setup in ubuntu 16.04

### ISSUE THREAD

**Issue by lfrodrigues** [chef-cookbooks/openldap#79] opened 2017-01-02 11:45 UTC
### Cookbook version
Latest from git

### Chef-client version
Chef: 12.17.44

### Platform Details
Ubuntu 16.04 - AWS

### Scenario:
I installed ldap using the the recipe but when I login with phpldapadmin I get the error "This base cannot be created with PLA." and can't edit anything.

If I install the package using apt-get ldap works fine and I can directory from phpldapadmin.

### Steps to Reproduce:

Install openldap with: 
```
    # configure ldap machine
    attribute ['openldap', 'tls_enabled'], false # TODO: need proper certificate for this
    attribute ['openldap', 'rootpw'], '{SSHA}XXXXXXXXXXXX'

    recipe 'openldap::server' 
````

### Expected Result:
phpldapadmin should be working but it is not

Am I missing something in configuration?

**Comment by lfrodrigues** [comment] 2017-01-02 13:48
Finally understood that this cookbook is not creating initial base. Maybe a note could be added in README making it more clear what needs to be done.

I can make a PR to add this. 

If anyone ends up in this issue and no PR is done to update README here's solution for CentOS:
http://www.idevelopment.info/data/LDAP/LDAP_Resources/OPENLDAP_Initialize_a_New_LDAP_Directory_CentOS5.shtml

**Comment by cheeseplus** [comment] 2017-03-15 20:25
This cookbook doesn't take care of populating a database and currently that is out of scope for it. If you'd like you can open up a PR but ideally we'd like to minimize the scope of this cookbook or put that in another cookbook. Closing this as it's not a bug.

**Closed by cheeseplus** 2017-03-15 20:25 UTC
Labels: Type: Bug
