### ISSUE TITLE
Broken slapd.con.erb 

### ISSUE THREAD

**Issue by finchr** [chef-cookbooks/openldap#92] opened 2017-05-22 21:35 UTC
### Cookbook version
3.0.3

### Chef-client version
12.18.31 & 12.19.36

### Platform Details
Vagrant, AWS, Ubuntu 12.04, 16.04)

### Scenario:
A slapd that will start

### Steps to Reproduce:
node.force_override['openldap']['slapd_type'] = 'consumer' 
include_recipe 'openldap::default'

### Expected Result:
That slapd will start with resulting slapd.conf

### Actual Result:
slapd failes with following error: 

slapd[6336]: /etc/ldap/slapd.conf: line 86: Error: parse_syncrepl_line: unable to parse " 

It looks like a copypasta error in slapd.conf.erb: 
diff -c slapd.conf.erb /tmp/
*** slapd.conf.erb	2017-05-21 15:56:19.358637954 -0700
--- /tmp/slapd.conf.erb	2017-05-22 14:33:20.476953616 -0700
***************
*** 104,110 ****
    scope=sub
    schemachecking=off
    bindmethod=simple
!   binddn="<%= node['openldap']['syncrepl_cn'] %>,<%= node['openldap']['basedn'] %>" read"
    starttls=<%= node['openldap']['syncrepl_use_tls'] %>
    credentials="<%= node['openldap']['slapd_replpw'] %>"
  <% end -%>
--- 104,110 ----
    scope=sub
    schemachecking=off
    bindmethod=simple
!   binddn="<%= node['openldap']['syncrepl_cn'] %>,<%= node['openldap']['basedn'] %>"
    starttls=<%= node['openldap']['syncrepl_use_tls'] %>
    credentials="<%= node['openldap']['slapd_replpw'] %>"
  <% end -%>
***************
*** 153,158 ****
  access to *
          by group.exact="cn=administrators,<%= node['openldap']['basedn'] %>" write
  <% if node['openldap']['slapd_type'] == "provider" -%>
!         by by dn="<%= node['openldap']['syncrepl_cn'] %>,<%= node['openldap']['basedn'] %>" read
  <% end -%>
          by * read
--- 153,158 ----
  access to *
          by group.exact="cn=administrators,<%= node['openldap']['basedn'] %>" write
  <% if node['openldap']['slapd_type'] == "provider" -%>
!         by dn="<%= node['openldap']['syncrepl_cn'] %>,<%= node['openldap']['basedn'] %>" read
  <% end -%>
          by * read

**Comment by dgoerger** [comment] 2017-05-25 15:33
On RHEL 7.3, slapd is able to initialize, but read permission is broken for non-admins. I've confirmed that changing `by by` to `by` restores read permissions and that openldap subsequently functions as intended. If any maintainers are about and wouldn't mind taking a look at PR #93, we'd like to repoint our systems back to upstream instead of the fork. Thanks!

**Comment by tas50** [comment] 2017-06-14 19:11
This should be fixed with the latest release on supermarket now

**Closed by tas50** 2017-06-14 19:11 UTC

**Comment by finchr** [comment] 2017-07-05 16:26
Hey, so it looks like the 3.1.0 version on the Chef Supermarket still has the broken code.
